/**
 * This file renders the pages and is autogenerated when creating a React app. It also sets up Google Analytics and
 * sends data to it using the tracking ID.
 */
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import ReactGA from 'react-ga';

ReactDOM.render(
	<React.StrictMode>
		<App />
	</React.StrictMode>,
	document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals

reportWebVitals();
ReactGA.initialize('UA-185264269-1'); // setup tracking ID for Google Analytics
ReactGA.pageview(window.location.pathname + window.location.search); //Send to Google Analytics current page

