name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Docker Compose Action
        uses: actions/checkout@v2
        with:
          # relative path to compose file
          compose-file: # optional, default is ./docker-compose.yml
          # additional options to pass to `docker-compose down` command
          down-flags: # optional, default is
